export class BuildingAccessManager{
  constructor(state,addPart,scene){this.state=state;this.addPart=addPart;this.scene=scene;this.ensureState()}
  ensureState(){this.state.buildingAccess={doorWidth:900,doorHeight:2100,windowWidth:1200,windowHeight:1000,stairRise:2800,stairRun:4200,stairWidth:1100,ladderHeight:2800,...(this.state.buildingAccess||{})};return this.state.buildingAccess}
  _base(){const p=this.state.creator&&Array.isArray(this.state.creator.lastCreatePosition)?this.state.creator.lastCreatePosition:null;const z=Number(this.state.workspace&&this.state.workspace.groundBaseCadZ);return p?[...p]:[0,0,Number.isFinite(z)?z:0]}
  _gid(prefix){return `${prefix}-${Date.now().toString(36)}-${Math.floor(Math.random()*46656).toString(36)}`}
  _part(name,params,position,extra={}){return this.addPart(extra.type||'box',{name,params,position,rotation:extra.rotation||[0,0,0],color:extra.color||0x9b7b5a,opacity:extra.opacity===undefined?1:extra.opacity,groupId:extra.groupId||null,entityKind:'building',physics:{enabled:true,bodyType:'static',mass:1,velocity:[0,0,0],restitution:.05,friction:.8,sleeping:false},components:{building:{enabled:true,primitive:extra.primitive||'access'},access:extra.access||{},...(extra.components||{})},motionAxes:extra.motionAxes||[],metadata:{walkable:extra.walkable!==false,...(extra.metadata||{})}},false)}
  _selectedWall(){return (this.state.selectedObjects?this.state.selectedObjects():[]).find(o=>o&&o.components&&o.components.building&&o.components.building.primitive==='wall')||null}
  _replaceWallWithOpening(wall,openingW,openingH,sill=0,kind='door'){if(!wall||!wall.params)return null;const W=Number(wall.params.width)||0,H=Number(wall.params.height)||0,D=Number(wall.params.depth)||100;if(W<=openingW+120||H<=openingH+sill+80)return null;const x=wall.position[0],y=wall.position[1],base=wall.position[2]-H/2,rot=Array.isArray(wall.rotation)?[...wall.rotation]:[0,0,0],gid=wall.groupId||this._gid('WALL');const side=(W-openingW)/2;const made=[];const common={groupId:gid,primitive:'wall',rotation:rot,color:wall.color||0x9b7b5a,metadata:{walkable:true,openingHost:true,openingType:kind}};made.push(this._part('壁 開口左',{width:side,height:H,depth:D},[x-(openingW+side)/2,y,base+H/2],common));made.push(this._part('壁 開口右',{width:side,height:H,depth:D},[x+(openingW+side)/2,y,base+H/2],common));if(sill>0)made.push(this._part('壁 窓下',{width:openingW,height:sill,depth:D},[x,y,base+sill/2],common));const topH=H-(sill+openingH);if(topH>40)made.push(this._part('壁 開口上',{width:openingW,height:topH,depth:D},[x,y,base+sill+openingH+topH/2],common));wall.visible=false;wall.metadata={...(wall.metadata||{}),replacedByOpening:true};if(this.scene&&this.scene.sync)this.scene.sync(wall);return {base:[x,y,base+sill],rotation:rot,parts:made,depth:D}}
  createDoor(opts={}){const c=this.ensureState(),wall=opts.wall||this._selectedWall(),wallOpen=wall?this._replaceWallWithOpening(wall,Number(opts.width)||c.doorWidth,Number(opts.height)||c.doorHeight,0,'door'):null,b=wallOpen?wallOpen.base:this._base(),w=Number(opts.width)||c.doorWidth,h=Number(opts.height)||c.doorHeight,t=Number(opts.thickness)||90,frame=Math.max(60,t*.85),gid=this._gid('DOOR'),x=b[0],y=b[1],z=b[2];const made=[],hostRot=wallOpen?wallOpen.rotation:[0,0,0];
    made.push(this._part('ドア枠 左',{width:frame,height:h+frame,depth:t},[x-w/2-frame/2,y,z+(h+frame)/2],{groupId:gid,primitive:'doorFrame',rotation:hostRot}));
    made.push(this._part('ドア枠 右',{width:frame,height:h+frame,depth:t},[x+w/2+frame/2,y,z+(h+frame)/2],{groupId:gid,primitive:'doorFrame',rotation:hostRot}));
    made.push(this._part('ドア枠 上',{width:w+frame*2,height:frame,depth:t},[x,y,z+h+frame/2],{groupId:gid,primitive:'doorFrame',rotation:hostRot}));
    const leaf=this._part('ドア',{width:w,height:h,depth:Math.max(35,t*.45)},[x,y,z+h/2],{groupId:gid,primitive:'door',rotation:hostRot,color:0x8b6546,access:{type:'door',groupId:gid,hingeSide:'left',open:false,closedPosition:[x,y,z+h/2],closedRotation:[...hostRot],openAngle:90,width:w},motionAxes:[{id:`${gid}:hinge`,name:'Door Hinge',type:'revolute',origin:[-w/2,0,0],direction:[0,0,1],min:0,max:110,value:0}],metadata:{walkable:false,doorLeaf:true,doorGroupId:gid}});made.push(leaf);
    const knob=this._part('ドアノブ',{radius:45,height:70},[x+w*.36,y-t*.35,z+h*.52],{type:'cylinder',rotation:[90,0,0],groupId:gid,primitive:'doorKnob',rotation:hostRot,color:0xc7a55b,walkable:false,access:{type:'doorKnob',doorId:leaf.id,groupId:gid,localOffset:[w*.36,-t*.35,h*.02]}});made.push(knob);
    this.state.selectedIds=[leaf.id];this.state.primaryId=leaf.id;return made}
  createWindow(opts={}){const c=this.ensureState(),wall=opts.wall||this._selectedWall(),sill0=Number(opts.sill)||900,wallOpen=wall?this._replaceWallWithOpening(wall,Number(opts.width)||c.windowWidth,Number(opts.height)||c.windowHeight,sill0,'window'):null,b=wallOpen?[wallOpen.base[0],wallOpen.base[1],wallOpen.base[2]-sill0]:this._base(),w=Number(opts.width)||c.windowWidth,h=Number(opts.height)||c.windowHeight,sill=Number(opts.sill)||900,t=Number(opts.thickness)||90,f=70,gid=this._gid('WINDOW'),x=b[0],y=b[1],z=b[2]+sill;const made=[],hostRot=wallOpen?wallOpen.rotation:[0,0,0];
    made.push(this._part('窓枠 左',{width:f,height:h,depth:t},[x-w/2-f/2,y,z+h/2],{groupId:gid,primitive:'windowFrame',rotation:hostRot}));made.push(this._part('窓枠 右',{width:f,height:h,depth:t},[x+w/2+f/2,y,z+h/2],{groupId:gid,primitive:'windowFrame',rotation:hostRot}));made.push(this._part('窓枠 上',{width:w+2*f,height:f,depth:t},[x,y,z+h+f/2],{groupId:gid,primitive:'windowFrame',rotation:hostRot}));made.push(this._part('窓枠 下',{width:w+2*f,height:f,depth:t},[x,y,z-f/2],{groupId:gid,primitive:'windowFrame',rotation:hostRot}));
    const glass=this._part('窓ガラス',{width:w,height:h,depth:18},[x,y,z+h/2],{groupId:gid,primitive:'window',rotation:hostRot,color:0x86b9cf,opacity:.35,walkable:false,access:{type:'window',groupId:gid,open:false}});made.push(glass);this.state.selectedIds=[glass.id];this.state.primaryId=glass.id;return made}
  createStairs(opts={}){const c=this.ensureState(),b=this._base(),rise=Number(opts.rise)||c.stairRise,run=Number(opts.run)||c.stairRun,width=Number(opts.width)||c.stairWidth,stepH=Math.max(120,Number(opts.stepHeight)||175),n=Math.max(2,Math.ceil(rise/stepH)),actualH=rise/n,stepD=run/n,gid=this._gid('STAIR'),made=[];for(let i=0;i<n;i++){const h=actualH*(i+1),x=b[0],y=b[1]-run/2+stepD*(i+.5),z=b[2]+h/2;made.push(this._part(`階段 ${i+1}`,{width,height:h,depth:stepD+8},[x,y,z],{groupId:gid,primitive:'stair',color:0x888888,metadata:{walkable:true,stair:true,stepIndex:i}}))}this.state.selectedIds=made.map(o=>o.id);this.state.primaryId=made[made.length-1]?.id||null;return made}
  createLadder(opts={}){const c=this.ensureState(),b=this._base(),height=Number(opts.height)||c.ladderHeight,width=Number(opts.width)||520,rail=55,rung=35,spacing=Math.max(180,Number(opts.rungSpacing)||280),gid=this._gid('LADDER'),made=[],x=b[0],y=b[1],z=b[2];made.push(this._part('ハシゴ 左',{width:rail,height,depth:rail},[x-width/2,y,z+height/2],{groupId:gid,primitive:'ladder',color:0x777777,metadata:{walkable:true,ladder:true}}));made.push(this._part('ハシゴ 右',{width:rail,height,depth:rail},[x+width/2,y,z+height/2],{groupId:gid,primitive:'ladder',color:0x777777,metadata:{walkable:true,ladder:true}}));for(let zz=spacing;zz<height;zz+=spacing)made.push(this._part('ハシゴ 段',{width:width+rail,height:rung,depth:140},[x,y,z+zz],{groupId:gid,primitive:'ladderRung',color:0x888888,metadata:{walkable:true,ladder:true}}));
    // Invisible stepped climb aid: lets the normal walkable-surface solver lift the avatar rung by rung.
    const steps=Math.max(3,Math.ceil(height/spacing));for(let i=0;i<steps;i++){const sh=height/steps*(i+1);made.push(this._part('ハシゴ ClimbAid',{width:Math.max(260,width*.7),height:Math.max(25,height/steps*.18),depth:220},[x,y+180,z+sh],{groupId:gid,primitive:'ladderAid',opacity:.03,color:0x66aacc,metadata:{walkable:true,ladderAid:true,helper:true}}))}this.state.selectedIds=made.map(o=>o.id);this.state.primaryId=made[made.length-1]?.id||null;return made}
  createStairsFitSelection(opts={}){const sel=this.state.selectedObjects?this.state.selectedObjects():[];if(sel.length<2)return this.createStairs(opts);const tops=sel.map(o=>({o,z:(Number(o.position&&o.position[2])||0)+(Number(o.params&&o.params.height)||0)/2})).sort((a,b)=>a.z-b.z);const rise=Math.max(200,tops[tops.length-1].z-tops[0].z);const a=tops[0].o.position,b=tops[tops.length-1].o.position;const run=Math.max(600,Math.hypot((b[0]-a[0]),(b[1]-a[1]))||rise*1.5);this.state.creator.lastCreatePosition=[a[0],a[1],tops[0].z];return this.createStairs({...opts,rise,run})}
  createLadderFitSelection(opts={}){const sel=this.state.selectedObjects?this.state.selectedObjects():[];if(!sel.length)return this.createLadder(opts);let lo=Infinity,hi=-Infinity,x=0,y=0;for(const o of sel){const h=Number(o.params&&o.params.height)||0,z=Number(o.position&&o.position[2])||0;lo=Math.min(lo,z-h/2);hi=Math.max(hi,z+h/2);x+=Number(o.position&&o.position[0])||0;y+=Number(o.position&&o.position[1])||0}this.state.creator.lastCreatePosition=[x/sel.length,y/sel.length,lo];return this.createLadder({...opts,height:Math.max(600,hi-lo)})}
  _doorLeaves(){return(this.state.objects||[]).filter(o=>o&&o.components&&o.components.access&&o.components.access.type==='door')}
  _resolveDoorSelection(){
    const ids=this.state.selectedIds||[],out=[];for(const o of this.state.objects||[]){if(!ids.includes(o.id))continue;const a=o.components&&o.components.access;if(a&&a.type==='door')out.push(o);else if(a&&a.type==='doorKnob'){const leaf=(this.state.objects||[]).find(x=>x.id===a.doorId);if(leaf&&!out.includes(leaf))out.push(leaf)}}
    return out;
  }
  _nearestDoor(){const leaves=this._doorLeaves();if(!leaves.length)return null;const p=this.state.avatar&&this.state.avatar.position||[0,0,0];let best=null,bd=Infinity;for(const d of leaves){const q=d.position||[0,0,0],dd=(q[0]-p[0])**2+(q[1]-p[1])**2+(q[2]-p[2])**2;if(dd<bd){bd=dd;best=d}}return best}
  _applyDoorState(leaf,open){
    if(!leaf)return null;const a=leaf.components.access||(leaf.components.access={type:'door'}),closedPos=Array.isArray(a.closedPosition)?a.closedPosition:[...(leaf.position||[0,0,0])],closedRot=Array.isArray(a.closedRotation)?a.closedRotation:[...(leaf.rotation||[0,0,0])],w=Number(a.width||leaf.params&&leaf.params.width)||900,baseYaw=Number(closedRot[2])||0,angle=(open?(Number(a.openAngle)||90):0),rad0=baseYaw*Math.PI/180,rad=(baseYaw+angle)*Math.PI/180;
    const hx=closedPos[0]-Math.cos(rad0)*w/2,hy=closedPos[1]-Math.sin(rad0)*w/2;leaf.position=[hx+Math.cos(rad)*w/2,hy+Math.sin(rad)*w/2,closedPos[2]];leaf.rotation=[Number(closedRot[0])||0,Number(closedRot[1])||0,baseYaw+angle];a.open=!!open;
    const axis=(leaf.motionAxes||[])[0];if(axis)axis.value=angle;this.scene&&this.scene.sync&&this.scene.sync(leaf);
    for(const knob of this.state.objects||[]){const ka=knob.components&&knob.components.access;if(!ka||ka.type!=='doorKnob'||ka.doorId!==leaf.id)continue;const off=ka.localOffset||[w*.36,-30,0],ox=Number(off[0])||0,oy=Number(off[1])||0;knob.position=[leaf.position[0]+Math.cos(rad)*ox-Math.sin(rad)*oy,leaf.position[1]+Math.sin(rad)*ox+Math.cos(rad)*oy,leaf.position[2]+(Number(off[2])||0)];knob.rotation=[90,0,baseYaw+angle];this.scene&&this.scene.sync&&this.scene.sync(knob)}
    return leaf;
  }
  toggleDoors({scope='selected',action='toggle'}={}){let doors=scope==='all'?this._doorLeaves():this._resolveDoorSelection();if(!doors.length){const d=this._nearestDoor();if(d)doors=[d]}if(!doors.length)return[];for(const d of doors){const next=action==='open'?true:action==='close'?false:!d.components.access.open;this._applyDoorState(d,next)}this.state.selectedIds=doors.map(d=>d.id);this.state.primaryId=doors[0].id;return doors}
  toggleDoor(){return this.toggleDoors({scope:'selected',action:'toggle'})[0]||null}

}
