function clone(v){return JSON.parse(JSON.stringify(v))}
export function ensureManufacturingPart(part){part.manufacturing=part.manufacturing&&typeof part.manufacturing==="object"?part.manufacturing:{};const m=part.manufacturing;m.partNumber=m.partNumber||part.objectId||part.id;m.revision=m.revision||"A";m.material=m.material||"UNSPECIFIED";m.massKg=Number(m.massKg)||0;m.cost=Number(m.cost)||0;m.stock=Number(m.stock)||0;m.process=Array.isArray(m.process)?m.process:[];m.repairHistory=Array.isArray(m.repairHistory)?m.repairHistory:[];return m}
export function ensureManufacturingState(state){state.manufacturing=state.manufacturing&&typeof state.manufacturing==="object"?state.manufacturing:{};const m=state.manufacturing;m.materialLibrary=Array.isArray(m.materialLibrary)&&m.materialLibrary.length?m.materialLibrary:[{id:"SS400",density:7850},{id:"S45C",density:7850},{id:"SUS304",density:7930},{id:"A5052",density:2680},{id:"A6061",density:2700},{id:"ABS",density:1040},{id:"PLA",density:1240},{id:"WOOD",density:650}];m.blueprints=Array.isArray(m.blueprints)?m.blueprints:[];return m}
export class ManufacturingCore{
  constructor(state){this.state=state;ensureManufacturingState(state)}
  bom(rootIds=null){const ids=rootIds?new Set(rootIds):null;return (this.state.objects||[]).filter(o=>!ids||ids.has(o.id)).map(o=>{const m=ensureManufacturingPart(o);return {objectId:o.objectId,id:o.id,name:o.name,partNumber:m.partNumber,revision:m.revision,material:m.material,massKg:m.massKg,cost:m.cost,stock:m.stock,groupId:o.groupId||null}})}
  setPart(part,data){const m=ensureManufacturingPart(part);Object.assign(m,clone(data||{}));return m}
  addProcess(part,step){const m=ensureManufacturingPart(part);m.process.push({id:`PROC${String(m.process.length+1).padStart(3,"0")}`,name:step.name||"Process",machine:step.machine||null,timeMin:Number(step.timeMin)||0,note:step.note||""});return m.process.at(-1)}
  addRepair(part,entry={}){const m=ensureManufacturingPart(part);const row={date:entry.date||new Date().toISOString(),worker:entry.worker||"",cost:Number(entry.cost)||0,note:entry.note||"",parts:clone(entry.parts||[])};m.repairHistory.push(row);return row}
  createBlueprint(part){const s=ensureManufacturingState(this.state);const bp={id:`BP${String(s.blueprints.length+1).padStart(4,"0")}`,sourceId:part.id,objectId:part.objectId,name:part.name,revision:ensureManufacturingPart(part).revision,createdAt:new Date().toISOString(),snapshot:{type:part.type,params:clone(part.params||{}),features:clone(part.features||[]),motionAxes:clone(part.motionAxes||[]),sockets:clone(part.sockets||[]),components:clone(part.components||{}),manufacturing:clone(part.manufacturing||{})}};s.blueprints.push(bp);return bp}
}
