import * as THREE from 'three';
const EPS=1e-5;
class Vertex{constructor(pos,normal){this.pos=pos;this.normal=normal}clone(){return new Vertex(this.pos.clone(),this.normal.clone())}flip(){this.normal.multiplyScalar(-1)}interpolate(o,t){return new Vertex(this.pos.clone().lerp(o.pos,t),this.normal.clone().lerp(o.normal,t).normalize())}}
class Plane{constructor(normal,w){this.normal=normal;this.w=w}clone(){return new Plane(this.normal.clone(),this.w)}flip(){this.normal.multiplyScalar(-1);this.w=-this.w}splitPolygon(poly,coplanarFront,coplanarBack,front,back){let type=0,types=[];for(const v of poly.vertices){const t=this.normal.dot(v.pos)-this.w;const vt=t<-EPS?2:t>EPS?1:0;type|=vt;types.push(vt)}if(type===0)(this.normal.dot(poly.plane.normal)>0?coplanarFront:coplanarBack).push(poly);else if(type===1)front.push(poly);else if(type===2)back.push(poly);else{const f=[],b=[];for(let i=0;i<poly.vertices.length;i++){const j=(i+1)%poly.vertices.length,ti=types[i],tj=types[j],vi=poly.vertices[i],vj=poly.vertices[j];if(ti!==2)f.push(vi);if(ti!==1)b.push(ti!==2?vi:vi.clone());if((ti|tj)===3){const t=(this.w-this.normal.dot(vi.pos))/this.normal.dot(vj.pos.clone().sub(vi.pos));const v=vi.interpolate(vj,t);f.push(v);b.push(v.clone())}}if(f.length>=3)front.push(new Polygon(f,poly.shared));if(b.length>=3)back.push(new Polygon(b,poly.shared))}}}
class Polygon{constructor(vertices,shared=null){this.vertices=vertices;this.shared=shared;this.plane=Polygon.plane(vertices)}clone(){return new Polygon(this.vertices.map(v=>v.clone()),this.shared)}flip(){this.vertices.reverse().forEach(v=>v.flip());this.plane.flip()}static plane(v){const a=v[0].pos,b=v[1].pos,c=v[2].pos,n=b.clone().sub(a).cross(c.clone().sub(a)).normalize();return new Plane(n,n.dot(a))}}
class Node{constructor(polygons=[]){this.plane=null;this.front=null;this.back=null;this.polygons=[];if(polygons.length)this.build(polygons)}clone(){const n=new Node();n.plane=this.plane?.clone()||null;n.front=this.front?.clone()||null;n.back=this.back?.clone()||null;n.polygons=this.polygons.map(p=>p.clone());return n}invert(){for(const p of this.polygons)p.flip();this.plane?.flip();this.front?.invert();this.back?.invert();[this.front,this.back]=[this.back,this.front]}clipPolygons(polygons){if(!this.plane)return polygons.slice();let front=[],back=[];for(const p of polygons)this.plane.splitPolygon(p,front,back,front,back);if(this.front)front=this.front.clipPolygons(front);if(this.back)back=this.back.clipPolygons(back);else back=[];return front.concat(back)}clipTo(bsp){this.polygons=bsp.clipPolygons(this.polygons);this.front?.clipTo(bsp);this.back?.clipTo(bsp)}allPolygons(){let p=this.polygons.slice();if(this.front)p=p.concat(this.front.allPolygons());if(this.back)p=p.concat(this.back.allPolygons());return p}build(polygons){if(!polygons.length)return;if(!this.plane)this.plane=polygons[0].plane.clone();const front=[],back=[];for(const p of polygons)this.plane.splitPolygon(p,this.polygons,this.polygons,front,back);if(front.length){if(!this.front)this.front=new Node();this.front.build(front)}if(back.length){if(!this.back)this.back=new Node();this.back.build(back)}}}
function csg(polygons){return {polygons,union(other){const a=new Node(this.polygons.map(p=>p.clone())),b=new Node(other.polygons.map(p=>p.clone()));a.clipTo(b);b.clipTo(a);b.invert();b.clipTo(a);b.invert();a.build(b.allPolygons());return csg(a.allPolygons())},subtract(other){const a=new Node(this.polygons.map(p=>p.clone())),b=new Node(other.polygons.map(p=>p.clone()));a.invert();a.clipTo(b);b.clipTo(a);b.invert();b.clipTo(a);b.invert();a.build(b.allPolygons());a.invert();return csg(a.allPolygons())},intersect(other){const a=new Node(this.polygons.map(p=>p.clone())),b=new Node(other.polygons.map(p=>p.clone()));a.invert();b.clipTo(a);b.invert();a.clipTo(b);b.clipTo(a);a.build(b.allPolygons());a.invert();return csg(a.allPolygons())}}}
export function meshToCSG(mesh){mesh.updateMatrixWorld(true);const g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();g.computeVertexNormals();const pos=g.attributes.position,nor=g.attributes.normal,normalMatrix=new THREE.Matrix3().getNormalMatrix(mesh.matrixWorld),polys=[];for(let i=0;i<pos.count;i+=3){const vs=[];for(let j=0;j<3;j++){const k=i+j,p=new THREE.Vector3().fromBufferAttribute(pos,k).applyMatrix4(mesh.matrixWorld),n=new THREE.Vector3().fromBufferAttribute(nor,k).applyMatrix3(normalMatrix).normalize();vs.push(new Vertex(p,n))}const area=vs[1].pos.clone().sub(vs[0].pos).cross(vs[2].pos.clone().sub(vs[0].pos)).lengthSq();if(area>EPS*EPS)polys.push(new Polygon(vs))}g.dispose();return csg(polys)}
export function csgToGeometry(solid){const positions=[],normals=[];for(const p of solid.polygons){for(let i=2;i<p.vertices.length;i++){for(const v of [p.vertices[0],p.vertices[i-1],p.vertices[i]]){positions.push(v.pos.x,v.pos.y,v.pos.z);normals.push(v.normal.x,v.normal.y,v.normal.z)}}}if(!positions.length)throw new Error('Boolean結果が空です');const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.computeBoundingBox();g.computeBoundingSphere();return g}
export function booleanGeometry(a,b,operation){const ca=meshToCSG(a),cb=meshToCSG(b);const result=operation==='join'?ca.union(cb):operation==='cut'?ca.subtract(cb):ca.intersect(cb);return csgToGeometry(result)}
