import * as THREE from "three";
const uid=(b,t,i)=>`${b}:${t}:${i}`;
export class BRepCore{
 build(part){let solid;if(part.type==="box")solid=this.box(part);else if(part.type==="cylinder")solid=this.cylinder(part);else if(part.type==="sphere")solid=this.sphere(part);else solid=this.approx(part);solid.diagnostics=this.diagnose(solid);solid.massProperties=this.mass(part,solid);part.brep=solid;return solid}
 v(b,i,p){return{id:uid(b,"vertex",i),type:"Vertex",position:p.toArray(),edgeIds:[],faceIds:[]}}
 e(b,i,a,c,curveType="line"){return{id:uid(b,"edge",i),type:"Edge",curveType,vertexIds:[a.id,c.id],halfEdgeIds:[],faceIds:[],length:new THREE.Vector3().fromArray(a.position).distanceTo(new THREE.Vector3().fromArray(c.position))}}
 f(b,i,vs,es,n,surfaceType="plane",area=0){return{id:uid(b,"face",i),type:"Face",surfaceType,outerLoopId:uid(b,"loop",i),innerLoopIds:[],vertexIds:vs,edgeIds:es,normal:n.toArray(),area}}
 connect(s){const vm=new Map(s.vertices.map(v=>[v.id,v])),em=new Map(s.edges.map(e=>[e.id,e]));for(const f of s.faces){for(const id of f.vertexIds){const v=vm.get(id);if(v&&!v.faceIds.includes(f.id))v.faceIds.push(f.id)}for(const id of f.edgeIds){const e=em.get(id);if(e&&!e.faceIds.includes(f.id))e.faceIds.push(f.id)}}for(const e of s.edges)for(const id of e.vertexIds){const v=vm.get(id);if(v&&!v.edgeIds.includes(e.id))v.edgeIds.push(e.id)}s.halfEdges=[];let h=0;for(const e of s.edges){const a={id:uid(s.bodyId,"halfedge",h++),edgeId:e.id,startVertexId:e.vertexIds[0],endVertexId:e.vertexIds[1],faceId:e.faceIds[0]||null},b={id:uid(s.bodyId,"halfedge",h++),edgeId:e.id,startVertexId:e.vertexIds[1],endVertexId:e.vertexIds[0],faceId:e.faceIds[1]||null};a.twinId=b.id;b.twinId=a.id;e.halfEdgeIds=[a.id,b.id];s.halfEdges.push(a,b)}s.loops=s.faces.map(f=>({id:f.outerLoopId,type:"Loop",faceId:f.id,edgeIds:[...f.edgeIds],orientation:"outer"}));s.shells=[{id:uid(s.bodyId,"shell",0),type:"Shell",faceIds:s.faces.map(f=>f.id),closed:true}];s.solidId=uid(s.bodyId,"solid",0);return s}
 box(p){const b=p.id,w=+p.params.width/2,h=+p.params.height/2,d=+p.params.depth/2,P=[[-w,-h,-d],[w,-h,-d],[w,h,-d],[-w,h,-d],[-w,-h,d],[w,-h,d],[w,h,d],[-w,h,d]].map(x=>new THREE.Vector3(...x)),V=P.map((x,i)=>this.v(b,i,x)),pairs=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]],E=pairs.map((x,i)=>this.e(b,i,V[x[0]],V[x[1]])),defs=[[[0,3,2,1],[3,2,1,0],[0,0,-1],(+p.params.width)*(+p.params.height)],[[4,5,6,7],[4,5,6,7],[0,0,1],(+p.params.width)*(+p.params.height)],[[0,1,5,4],[0,9,4,8],[0,-1,0],(+p.params.width)*(+p.params.depth)],[[3,7,6,2],[11,6,10,2],[0,1,0],(+p.params.width)*(+p.params.depth)],[[0,4,7,3],[8,7,11,3],[-1,0,0],(+p.params.height)*(+p.params.depth)],[[1,2,6,5],[1,10,5,9],[1,0,0],(+p.params.height)*(+p.params.depth)]],F=defs.map((x,i)=>this.f(b,i,x[0].map(j=>V[j].id),x[1].map(j=>E[j].id),new THREE.Vector3(...x[2]),"plane",x[3]));return this.connect({bodyId:b,bodyType:"box",vertices:V,edges:E,faces:F})}
 cylinder(p){const b=p.id,r=+p.params.radius,h=+p.params.height/2,n=24,V=[];for(let y of [-h,h])for(let i=0;i<n;i++){const a=i/n*Math.PI*2;V.push(this.v(b,V.length,new THREE.Vector3(Math.cos(a)*r,y,Math.sin(a)*r)))}const E=[];for(let i=0;i<n;i++){E.push(this.e(b,E.length,V[i],V[(i+1)%n],"arc"));E.push(this.e(b,E.length,V[n+i],V[n+(i+1)%n],"arc"));E.push(this.e(b,E.length,V[i],V[n+i]))}const F=[this.f(b,0,V.slice(0,n).map(v=>v.id),E.filter((_,i)=>i%3===0).map(e=>e.id),new THREE.Vector3(0,-1,0),"plane",Math.PI*r*r),this.f(b,1,V.slice(n).map(v=>v.id),E.filter((_,i)=>i%3===1).map(e=>e.id),new THREE.Vector3(0,1,0),"plane",Math.PI*r*r)];for(let i=0;i<n;i++){const q=(i+1)%n;F.push(this.f(b,2+i,[V[i].id,V[q].id,V[n+q].id,V[n+i].id],[E[i*3].id,E[q*3+2].id,E[i*3+1].id,E[i*3+2].id],new THREE.Vector3(Math.cos((i+.5)/n*Math.PI*2),0,Math.sin((i+.5)/n*Math.PI*2)),"cylinder",2*Math.PI*r/n*(h*2)))}return this.connect({bodyId:b,bodyType:"cylinder",vertices:V,edges:E,faces:F})}
 sphere(p){const b=p.id,r=+p.params.radius,V=[this.v(b,0,new THREE.Vector3(0,r,0)),this.v(b,1,new THREE.Vector3(0,-r,0))],F=[this.f(b,0,V.map(v=>v.id),[],new THREE.Vector3(0,1,0),"sphere",4*Math.PI*r*r)];return this.connect({bodyId:b,bodyType:"sphere",vertices:V,edges:[],faces:F})}
 approx(p){return this.connect({bodyId:p.id,bodyType:"mesh-approximation",vertices:[],edges:[],faces:[]})}
 mass(p,s){let v=0;if(p.type==="box")v=+p.params.width*+p.params.height*+p.params.depth;else if(p.type==="cylinder")v=Math.PI*(+p.params.radius)**2*+p.params.height;else if(p.type==="sphere")v=4/3*Math.PI*(+p.params.radius)**3;return{volume:v,centerOfMass:[...p.position],surfaceArea:s.faces.reduce((a,f)=>a+(+f.area||0),0)}}
 diagnose(s){const issues=[];for(const e of s.edges){if(e.length<1e-8)issues.push({severity:"error",type:"zero-length-edge",id:e.id});if(e.faceIds.length>2)issues.push({severity:"error",type:"non-manifold-edge",id:e.id})}for(const f of s.faces)if(f.area<1e-8)issues.push({severity:"error",type:"zero-area-face",id:f.id});if(!issues.length)issues.push({severity:"ok",type:"valid",id:s.solidId});return issues}
 serialize(p){return structuredClone(p.brep||this.build(p))}
}