function clone(v){return JSON.parse(JSON.stringify(v));}
function clamp(v,a,b){v=Number(v);return Math.max(a,Math.min(b,Number.isFinite(v)?v:a));}
function id(prefix){return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random()*46656).toString(36).toUpperCase()}`}
function ensureWallet(root,userId){root.wallets=root.wallets||{};if(!root.wallets[userId])root.wallets[userId]={balance:1000,earned:0,spent:0};return root.wallets[userId];}

export class MarketplaceManager{
  constructor(state,addPart,recipeManager){this.state=state;this.addPart=addPart;this.recipeManager=recipeManager;this.ensureState();}
  ensureState(){
    this.state.marketplace=this.state.marketplace||{};const m=this.state.marketplace;
    m.currentUserId=m.currentUserId||'PLAYER';m.platformContributionRate=clamp(m.platformContributionRate===undefined?1:m.platformContributionRate,0,10);m.platformFund=Number(m.platformFund)||0;m.adRevenuePool=Number(m.adRevenuePool)||0;m.adDistributionRate=clamp(m.adDistributionRate===undefined?30:m.adDistributionRate,0,100);m.ratingReward=Math.max(0,Number(m.ratingReward)||1);m.markets=Array.isArray(m.markets)?m.markets:[];m.listings=Array.isArray(m.listings)?m.listings:[];m.purchases=Array.isArray(m.purchases)?m.purchases:[];m.ratings=Array.isArray(m.ratings)?m.ratings:[];m.ledger=Array.isArray(m.ledger)?m.ledger:[];m.wallets=m.wallets||{};ensureWallet(m,m.currentUserId);return m;
  }
  setCurrentUser(userId){const m=this.ensureState();m.currentUserId=String(userId||'PLAYER').trim()||'PLAYER';ensureWallet(m,m.currentUserId);return m.currentUserId;}
  wallet(userId){const m=this.ensureState();return ensureWallet(m,userId||m.currentUserId);}
  createMarket(opts={}){const m=this.ensureState(),ownerId=String(opts.ownerId||m.currentUserId),feeRate=clamp(opts.feeRate===undefined?5:opts.feeRate,0,20);const market={id:id('MKT'),name:String(opts.name||'New Market'),ownerId,feeRate,createdAt:new Date().toISOString(),enabled:true,entityObjectId:null};m.markets.push(market);return market;}
  placeMarketEntity(marketId,position=[0,0,0]){const market=this.ensureState().markets.find(x=>x.id===marketId);if(!market)throw new Error('マーケットが見つかりません');if(!this.addPart)return null;const kiosk=this.addPart('box',{name:`Market: ${market.name}`,params:{width:1800,height:2200,depth:900},position:[position[0]||0,position[1]||0,(position[2]||0)+1100],color:0x2c6e8e,opacity:1,entityKind:'building',components:{marketplace:{enabled:true,marketId:market.id,ownerId:market.ownerId}},metadata:{walkable:false,marketEntity:true}},false);market.entityObjectId=kiosk&&kiosk.id||null;return kiosk;}
  updateMarket(id_,patch={}){const x=this.ensureState().markets.find(m=>m.id===id_);if(!x)throw new Error('マーケットが見つかりません');if(patch.name!==undefined)x.name=String(patch.name||x.name);if(patch.feeRate!==undefined)x.feeRate=clamp(patch.feeRate,0,20);return x;}
  createListing(recipeId,marketId,opts={}){const m=this.ensureState(),recipe=(this.recipeManager&&this.recipeManager.list({})||[]).find(r=>r.id===recipeId),market=m.markets.find(x=>x.id===marketId);if(!recipe)throw new Error('Recipe / Blueprintが見つかりません');if(!market)throw new Error('マーケットが見つかりません');const material=Math.max(0,Number(opts.materialCost)||0),labor=Math.max(0,Number(opts.laborCost)||0),margin=Math.max(0,Number(opts.margin)||0),suggested=material+labor+margin,price=Math.max(0,Number(opts.price)||suggested);const listing={id:id('LST'),recipeId,marketId,sellerId:String(opts.sellerId||m.currentUserId),title:String(opts.title||recipe.name),price,materialCost:material,laborCost:labor,margin,license:String(opts.license||'use'),published:true,createdAt:new Date().toISOString(),sales:0,ratingAverage:0,ratingCount:0};m.listings.push(listing);return listing;}
  settlement(listing){const m=this.ensureState(),market=m.markets.find(x=>x.id===listing.marketId);if(!market)throw new Error('マーケットが見つかりません');const price=Math.max(0,Number(listing.price)||0),feeRate=clamp(market.feeRate,0,20)/100,platformRate=clamp(m.platformContributionRate,0,10)/100,marketGross=price*feeRate,sellerGross=price-marketGross,sellerContribution=sellerGross*platformRate,marketContribution=marketGross*platformRate;return{price,marketFeeRate:feeRate*100,platformRate:platformRate*100,sellerGross,marketGross,sellerContribution,marketContribution,sellerNet:sellerGross-sellerContribution,marketNet:marketGross-marketContribution,platformTotal:sellerContribution+marketContribution};}
  buy(listingId,buyerId){const m=this.ensureState(),listing=m.listings.find(x=>x.id===listingId&&x.published);if(!listing)throw new Error('商品が見つかりません');buyerId=String(buyerId||m.currentUserId);if(buyerId===listing.sellerId)throw new Error('自分の商品は購入できません');const s=this.settlement(listing),buyer=this.wallet(buyerId);if(buyer.balance<s.price)throw new Error('ポイント残高が不足しています');const seller=this.wallet(listing.sellerId),market=m.markets.find(x=>x.id===listing.marketId),admin=this.wallet(market.ownerId);buyer.balance-=s.price;buyer.spent+=s.price;seller.balance+=s.sellerNet;seller.earned+=s.sellerNet;admin.balance+=s.marketNet;admin.earned+=s.marketNet;m.platformFund+=s.platformTotal;listing.sales=(listing.sales||0)+1;const purchase={id:id('BUY'),listingId,buyerId,sellerId:listing.sellerId,marketId:listing.marketId,price:s.price,settlement:s,createdAt:new Date().toISOString()};m.purchases.push(purchase);m.ledger.push({type:'purchase',...purchase});return purchase;}
  canRate(listingId,userId){const m=this.ensureState();return m.purchases.some(p=>p.listingId===listingId&&p.buyerId===userId)&&!m.ratings.some(r=>r.listingId===listingId&&r.userId===userId);}
  rate(listingId,stars,userId){const m=this.ensureState();userId=String(userId||m.currentUserId);stars=Math.round(clamp(stars,1,5));if(!this.canRate(listingId,userId))throw new Error('購入済みで未評価の商品のみ評価できます');const listing=m.listings.find(x=>x.id===listingId);if(!listing)throw new Error('商品が見つかりません');const r={id:id('RATE'),listingId,userId,stars,createdAt:new Date().toISOString()};m.ratings.push(r);const all=m.ratings.filter(x=>x.listingId===listingId);listing.ratingCount=all.length;listing.ratingAverage=all.reduce((a,x)=>a+x.stars,0)/all.length;const reward=Math.min(m.ratingReward,m.adRevenuePool);if(reward>0){m.adRevenuePool-=reward;const w=this.wallet(userId);w.balance+=reward;w.earned+=reward;m.ledger.push({type:'rating-reward',listingId,userId,amount:reward,createdAt:new Date().toISOString()});}return{rating:r,reward};}
  addAdRevenue(points){const m=this.ensureState();points=Math.max(0,Number(points)||0);m.adRevenuePool+=points;m.ledger.push({type:'ad-revenue',amount:points,createdAt:new Date().toISOString()});return m.adRevenuePool;}
  distributeAdRevenue(){const m=this.ensureState(),rate=clamp(m.adDistributionRate,0,100)/100,total=Math.min(m.adRevenuePool,m.adRevenuePool*rate);const users=new Set();m.listings.forEach(l=>{if(l.sellerId)users.add(l.sellerId);const mk=m.markets.find(x=>x.id===l.marketId);if(mk&&mk.ownerId)users.add(mk.ownerId)});m.purchases.forEach(p=>{if(p.buyerId)users.add(p.buyerId)});m.ratings.forEach(r=>{if(r.userId)users.add(r.userId)});if(total<=0||!users.size)return{total:0,perUser:0,users:0};const per=total/users.size;users.forEach(uid=>{const w=this.wallet(uid);w.balance+=per;w.earned+=per});m.adRevenuePool-=total;m.ledger.push({type:'ad-distribution',amount:total,perUser:per,users:[...users],createdAt:new Date().toISOString()});return{total,perUser:per,users:users.size};}
  listingView(){const m=this.ensureState(),recipes=this.recipeManager&&this.recipeManager.list({})||[];return m.listings.map(l=>{const r=recipes.find(x=>x.id===l.recipeId),market=m.markets.find(x=>x.id===l.marketId);return{...l,recipe:r||null,market:market||null,settlement:this.settlement(l)}});}
}
