import * as THREE from 'three';
export class SpatialPanelManager{
  constructor(state,scene,viewport,onChange=()=>{}){this.state=state;this.scene=scene;this.viewport=viewport;this.onChange=onChange;this.state.workspaceItems=Array.isArray(this.state.workspaceItems)?this.state.workspaceItems:[];this.host=document.createElement('div');this.host.className='spatialPanelLayer';viewport.append(this.host);this.dom=new Map();this.render();scene.addLoopHook?.(()=>this.updatePositions())}
  nextId(prefix){let n=1,id;do{id=`${prefix}${String(n++).padStart(3,'0')}`}while(this.state.workspaceItems.some(x=>x.id===id));return id}
  create(type,position=[0,0,80]){const item=type==='node'?{id:this.nextId('NODE'),type,title:'Node Graph',position:[...position],content:'TIME → IF → MOVE'}:{id:this.nextId('DOC'),type:'document',title:'Document',position:[...position],content:'設計メモを入力…'};this.state.workspaceItems.push(item);this.render();this.onChange();return item}
  remove(id){this.state.workspaceItems=this.state.workspaceItems.filter(x=>x.id!==id);this.render();this.onChange()}
  render(){this.host.innerHTML='';this.dom.clear();for(const item of this.state.workspaceItems){const el=document.createElement('div');el.className=`spatialPanel ${item.type}`;el.dataset.id=item.id;el.innerHTML=`<div class="spatialPanelHead"><b>${item.type==='node'?'◫':'📄'} <input class="spTitle" value="${this.esc(item.title||item.id)}"></b><button class="spClose">×</button></div><textarea class="spContent">${this.esc(item.content||'')}</textarea><div class="spFoot">${item.id} · X${item.position[0].toFixed(0)} Y${item.position[1].toFixed(0)} Z${item.position[2].toFixed(0)}</div>`;this.host.append(el);this.dom.set(item.id,el);el.querySelector('.spClose').onclick=()=>this.remove(item.id);el.querySelector('.spTitle').onchange=e=>{item.title=e.target.value;this.onChange()};el.querySelector('.spContent').oninput=e=>{item.content=e.target.value;this.onChange(false)};}
    this.updatePositions();
  }
  esc(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
  updatePositions(){const rect=this.viewport.getBoundingClientRect();for(const item of this.state.workspaceItems){const el=this.dom.get(item.id);if(!el)continue;const v=new THREE.Vector3(item.position[0],item.position[2],item.position[1]).project(this.scene.camera);const visible=v.z>-1&&v.z<1;el.style.display=visible?'block':'none';el.style.left=`${(v.x+1)*rect.width/2}px`;el.style.top=`${(1-v.y)*rect.height/2}px`;}}
}
